version: "3"
services:
  api-spring:
    image: raulluna/chumbi_container:1
    build: .
    networks:
      - net-cloud
    container_name: mongevaluacion
    depends_on:
      - mongo_container
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_container:27017/mongeva
      - SPRING_DATA_MONGODB_USERNAME=test
      - SPRING_DATA_MONGODB_PASSWORD=passwordvalue
    ports:
      - 8080:8080

  mongo_container:
    image: mongo:latest
    networks:
      - net-cloud
    container_name: mongo_container
    ports:
      - 2023:27017
    environment:
      - MONGO_INITDB_DATABASE=mongeva
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=passwordvalue

networks:
  net-cloud: