version: "3"
services:
  mongodb:
    image: raulluna/spring-mongo:1.0
    ports:
      - 8081:8080
    volumes:
      - ./data:/data/db
  mongo:
    image: mongo
    ports:
      - 2002:27017
    volumes:
      - ./data:/data/db