version: "3"
services:
  mongo-spring:
    image: raulluna/mongo-spring
    ports:
      - "2002:27017"
    volumes:
      - ./data:/data/db

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db